all:
	go build *.go
run1:
	go run *.go -type=s -id=1
run2:
	go run *.go -type=s -id=2
run3:
	go run *.go -type=s -id=3
run4:
	go run *.go -type=c -id=4
run5:
	go run *.go -type=c -id=5
clear:
	rm const