all:
	go build *.go
run0:
	go run *.go -type=server -id=0
run1:
	go run *.go -type=server -id=1
run2:
	go run *.go -type=server -id=2
run3:
	go run *.go -type=client -id=0
run4:
	go run *.go -type=client -id=1

clear:
	rm const