all:
	go build *.go
run1:
	go run *.go -type=server -id=1
run2:
	go run *.go -type=server -id=2
run3:
	go run *.go -type=server -id=3
run4:
	go run *.go -type=client -id=4
run5:
	go run *.go -type=client -id=5
clear:
	rm const